### ISSUE TITLE
Failed to run image_generator.py because randint arg is negative number

### ISSUE THREAD

**Issue by yukkysaito** [leetenki/YOLOv2#13]
@leetenki 
Failed to run image_generator.py because randint arg is negative number
I got the errors in the  image_generator.py .
First:
```
  File "image_generate.py", line 24, in <module>
    delta_val_scale=0.5
  File "/home/autoware/workspace/chainer_ws/YOLOv2/lib/image_generator.py", line 171, in generate_samples
    tmp_image, bbox = random_overlay_image(sample_image, item, minimum_crop)
  File "/home/autoware/workspace/chainer_ws/YOLOv2/lib/image_generator.py", line 76, in random_overlay_image
    x = int(np.random.randint(src_w-scale_item_w) - shift_item_w)
  File "mtrand.pyx", line 977, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:16117)
ValueError: low >= high
```

Second:
```
loading image generator...
loading model...
start training
Traceback (most recent call last):
  File "darknet19_train.py", line 62, in <module>
    delta_val_scale=0.5
  File "/home/autoware/workspace/chainer_ws/YOLOv2/lib/image_generator.py", line 161, in generate_samples
    bg = self.bgs[np.random.randint(len(self.bgs))]
  File "mtrand.pyx", line 977, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:16117)
ValueError: low >= high
```

**Comment by suishii** [comment]
Do you fix this problem? I meet the same error,but I do not know how to fix it.

**Comment by Siii92** [comment]
I meet the same error too. If you fixed the problem, Could you tell me how to fix it?

RuntimeWarning: divide by zero encountered in long_scalars
  return box_intersection(a, b) / box_union(a, b)
Traceback (most recent call last):
  File "image_generate.py", line 26, in <module>
    delta_val_scale=0.5
  File "/home/dl-box/YOLOv2-master/image_generator.py", line 172, in generate_samples
    tmp_image, bbox = random_overlay_image(sample_image, item, minimum_crop)
  File "/home/dl-box/YOLOv2-master/image_generator.py", line 77, in random_overlay_image
    x = int(np.random.randint(src_w-scale_item_w) - shift_item_w)
  File "mtrand.pyx", line 885, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:7264)
ValueError: low >= high

**Comment by suishii** [comment]
Do you fix this error? If you fix it , Could you tell me how do you fix it? THANK YOU

**Comment by yuma116** [comment]
I have same problems. But, I can't fix this code.

**Comment by suishii** [comment]
In my case, I just redefine the value of minimum_crop, the value is smaller than 0.85 in the image_generator.py

**Comment by Siii92** [comment]
if src_h <= scale_item_h:
        src_h, scale_item_h = scale_item_h, src_h
    sh = src_h - scale_item_h

    a = np.random.randint(sh)
    y = int(a - shift_item_h)

    if src_w <= scale_item_w:
        src_w, scale_item_w = scale_item_w, src_w
    sw = src_w - scale_item_w

    b = np.random.randint(sw)
    x = int(b - shift_item_w)

try it, and tell me the results.

**Comment by suishii** [comment]
I just fix the minimum_crop to a smaller value than before, I chose 0.75 . And  the code is gone.

**Comment by kuochiyoug** [comment]
I fixed it by switching random_overlay_image() function to following scripts,
```
def random_overlay_image(src_image, overlay_image, minimum_crop):
    src_h, src_w = src_image.shape[:2]
    overlay_h, overlay_w = overlay_image.shape[:2]
    shift_item_h, shift_item_w = overlay_h * (1-minimum_crop), overlay_w * (1-minimum_crop)
    scale_item_h, scale_item_w = overlay_h * (minimum_crop*2-1), overlay_w * (minimum_crop*2-1)
    y_max = src_h-scale_item_h
    x_max = src_w-scale_item_w
    if y_max > 0:
        y = int(np.random.randint(src_h-scale_item_h) - shift_item_h)
    else:
        y = int(- shift_item_h)

    if x_max > 0:
        x = int(np.random.randint(src_w-scale_item_w) - shift_item_w)
    else:
        x = int(-shift_item_w)
    image = overlay(src_image, overlay_image, x, y)
    bbox = ((np.maximum(x, 0), np.maximum(y, 0)), (np.minimum(x+overlay_w, src_w-1), np.minimum(y+overlay_h, src_h-1)))

    return image, bbox
```
Please have a try
