### ISSUE TITLE
Error in yolov2.py AttributeError

### ISSUE THREAD

**Issue by Siii92** [leetenki/YOLOv2#15]
I encountered this error in yolov2.py 
Could you tell me how to fix it.
 >> python yolov2_train.py

loading image generator...
item_files = ...
loading initial model...
start training
Traceback (most recent call last):
  File "yolov2_train.py", line 82, in <module>
    loss = model(x, t)
  File "/home/dl-box/YOLOv2/yolov2.py", line 168, in __call__
    x_shift = Variable(np.broadcast_to(np.arange(grid_w), x.shape[1:]))
AttributeError: 'module' object has no attribute 'broadcast_to'

**Comment by Siii92** [comment]
I resolve this problem. I have used numpy ver1.08, but upgrade ver1.12.
