### ISSUE TITLE
error in darknet19_train.py

### ISSUE THREAD

**Issue by kilometer0101** [leetenki/YOLOv2#17]
After stat training, I encountered this error in darknet19_train.py
Do you have information about this?

Traceback (most recent call last):

  File "<ipython-input-6-2bd15229ae55>", line 75, in <module>
    y, loss, accuracy = model(x, one_hot_t)

  File "/Users/-/darknet19.py", line 122, in __call__
    y = self.predictor(x)

  File "/Users/-/darknet19.py", line 85, in __call__
    h = F.leaky_relu(self.bias1(self.bn1(self.conv1(x), test=not self.train, finetune=self.finetune)), slope=0.1)

  File "/Users/-/.pyenv/versions/anaconda3-4.3.1/envs/py3yolo/lib/python3.5/site-packages/chainer/links/normalization/batch_normalization.py", line 117, in __call__
    kwargs, test='test argument is not supported anymore. '

  File "/Users/-/.pyenv/versions/anaconda3-4.3.1/envs/py3yolo/lib/python3.5/site-packages/chainer/utils/argument.py", line 4, in check_unexpected_kwargs
    raise ValueError(message)

ValueError: test argument is not supported anymore. Use chainer.using_config

**Comment by kakutit** [comment]
i think your chainer's version is not 1.17.0(i guess your version should be the newest)
maybe you can solve it by changing the chainer's version.
